language: swift
osx_image: xcode10.2
sudo: false
script:
  - xcodebuild -project XColor.xcodeproj -scheme "XColor iOS" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6' clean test
  - xcodebuild -project XColor.xcodeproj -scheme "XColor tvOS" -destination 'platform=tvOS Simulator,name=Apple TV' clean test
  - xcodebuild -project XColor.xcodeproj -scheme "XColor watchOS" -destination 'platform=watchOS Simulator,name=Apple Watch - 38mm' clean build
after_success:
  - bash <(curl -s https://codecov.io/bash)
