language: swift
osx_image: xcode10.2
sudo: false
script:
  - xcodebuild -project XColor.xcodeproj -scheme XColor -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6' clean test
after_success:
  - bash <(curl -s https://codecov.io/bash)
