language: swift
osx_image: xcode10.2
xcode_sdk: iphonesimulator10.1
xcode_destination: platform=iOS Simulator,OS=10.1,name=iPhone 6
sudo: false
script:
  - xcodebuild -scheme XColor -sdk iphonesimulator 'platform=iOS Simulator,name=iPhone 6,OS=10.1' build test
after_success:
  - bash <(curl -s https://codecov.io/bash)
